# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20160819_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='birthday',
            field=models.DateField(default='2016-08-20'),
            preserve_default=False,
        ),
    ]
