# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_userlog_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='username',
            new_name='alias',
        ),
        migrations.AddField(
            model_name='userlog',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
